services:
  - type: web
    name: nexaerp-api
    runtime: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health/ready
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WEB_ORIGIN
        value: https://www.nexaerp.dev
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: AUTO_MIGRATE
        value: 'false'
